<script setup>
import { ref } from 'vue'
import { router, useForm } from '@inertiajs/vue3'
import AppLayout from '@/Layouts/AppLayout.vue'
import BaseCard from '@/Components/BaseCard.vue'
import DataTable from '@/Components/DataTable.vue'
import PageHeader from '@/Components/PageHeader.vue'
import { confirmDanger } from '@/Composables/useNotifications'

const props = defineProps({ records: Object, filters: Object, files: Array })
const equipmentFilter = ref(props.filters?.equipment_file_id || '')
const showModal = ref(false)
const editing = ref(null)
const query = new URLSearchParams(window.location.search)
const form = useForm({ equipment_file_id: equipmentFilter.value || '', record_date: new Date().toISOString().slice(0,10), area: query.get('area') || '', support_number: '', content_summary: '', observations: '' })
const columns = [{key:'record_date',label:'Fecha'},{key:'equipment',label:'Expediente'},{key:'support_number',label:'Soporte'},{key:'content_summary',label:'Contenido'},{key:'actions',label:'Acciones'}]
const applyFilter = () => router.get('/control-soportes', { equipment_file_id: equipmentFilter.value || undefined }, { preserveState:true, replace:true })
const openCreate = () => { editing.value=null; form.reset(); form.equipment_file_id = equipmentFilter.value || ''; form.record_date = new Date().toISOString().slice(0,10); form.area = query.get('area') || ''; form.clearErrors(); showModal.value=true }
const openEdit = (row) => { editing.value=row; Object.assign(form,{ equipment_file_id: row.equipment_file_id, record_date: row.record_date || '', area: row.area || '', support_number: row.support_number, content_summary: row.content_summary || '', observations: row.observations || '' }); form.clearErrors(); showModal.value=true }
const submit = () => editing.value ? form.put(`/control-soportes/${editing.value.id}`, { onSuccess:()=> showModal.value=false }) : form.post('/control-soportes', { onSuccess:()=> showModal.value=false })
const destroy = async (row) => { if (!await confirmDanger({ title:'Eliminar control de soporte', text:'Se eliminara el registro de soporte.', confirmText:'Si, eliminar' })) return; router.delete(`/control-soportes/${row.id}`) }
</script>
<template><AppLayout><div class="mx-auto max-w-7xl space-y-6"><PageHeader eyebrow="Historial" title="Control de Soportes" description="Registro de soportes, contenido y observaciones por expediente."><template #actions><button class="app-button-primary" @click="openCreate">Nuevo control</button></template></PageHeader><BaseCard><select v-model="equipmentFilter" class="app-select max-w-md" @change="applyFilter"><option value="">Todos los expedientes</option><option v-for="file in files" :key="file.id" :value="file.id">{{ file.file_number }} - {{ file.inventory_number }}</option></select></BaseCard><DataTable client-table :columns="columns" :data="records"><template #cell-equipment="{ row }"><div><p class="font-medium text-slate-900 dark:text-slate-100">{{ row.equipment_file?.file_number }}</p><p class="text-xs text-slate-500 dark:text-slate-400">{{ row.area || row.equipment_file?.inventory_number }}</p></div></template><template #cell-content_summary="{ row }"><span class="text-slate-700 dark:text-slate-200">{{ row.content_summary || '-' }}</span></template><template #cell-actions="{ row }"><div class="flex justify-end gap-2"><button class="app-button-secondary px-3 py-2 text-xs" @click="openEdit(row)">Editar</button><button class="app-button-danger px-3 py-2 text-xs" @click="destroy(row)">Eliminar</button></div></template></DataTable></div><Teleport to="body"><div v-if="showModal" class="fixed inset-0 z-50 flex items-center justify-center px-4"><div class="fixed inset-0 bg-slate-950/70 backdrop-blur-sm" @click="showModal=false" /><div class="surface-card relative z-10 w-full max-w-3xl p-6"><h3 class="mb-5 text-xl font-semibold text-slate-950 dark:text-slate-100">{{ editing ? 'Editar control de soporte' : 'Nuevo control de soporte' }}</h3><form class="space-y-5" @submit.prevent="submit"><div class="grid gap-5 md:grid-cols-3"><select v-model="form.equipment_file_id" class="app-select"><option value="">Expediente...</option><option v-for="file in files" :key="file.id" :value="file.id">{{ file.file_number }}</option></select><input v-model="form.record_date" type="date" class="app-input" /><input v-model="form.area" type="text" class="app-input" placeholder="Area" /></div><input v-model="form.support_number" type="text" class="app-input" placeholder="No. consecutivo del soporte" /><textarea v-model="form.content_summary" rows="3" class="app-input" placeholder="Contenido fundamental del soporte"></textarea><textarea v-model="form.observations" rows="3" class="app-input" placeholder="Observaciones"></textarea><div class="flex justify-end gap-3 border-t border-slate-200/80 pt-4 dark:border-slate-800"><button type="button" class="app-button-secondary" @click="showModal=false">Cancelar</button><button type="submit" class="app-button-primary" :disabled="form.processing">{{ form.processing ? 'Guardando...' : 'Guardar' }}</button></div></form></div></div></Teleport></AppLayout></template>
